In [2]:
#Shishir Khanal
#01/17/2023
#Vectors and Matrices in Julia

In [3]:
#column vector
cvec = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [5]:
#column vector
rvec = [1 2 3 4 5]

1×5 Matrix{Int64}:
 1  2  3  4  5

In [6]:
mat = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [8]:
#Column vector
#comma and semicolon both create a column vector but they cant beused simultaneously
cvec = [1; 2; 3; 4; 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [9]:
ndims(cvec)

1

In [10]:
#Number of Dimensions
ndims(rvec)

2

In [11]:
ndims(mat)

2

In [13]:
#Length of rows and columns
size(mat)

(4, 3)

In [14]:
#length of row
size(mat, 1)

4

In [15]:
#length of column
size(mat, 2)

3

In [16]:
mat

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [18]:
#access element at row-2 and column-3
mat[2, 3]

6

In [19]:
mat[end, end]

12

In [20]:
mat[3]

7

In [21]:
mat[5]

2

In [22]:
mat[2:4,2:3]

3×2 Matrix{Int64}:
  5   6
  8   9
 11  12

In [23]:
mat[2, :]

3-element Vector{Int64}:
 4
 5
 6

In [26]:
cvec1 = [1, 2, 3, 4, 5]
cvec2 = [6, 7, 8, 9, 10]
cvec3 = [11, 12, 13, 14, 15]

5-element Vector{Int64}:
 11
 12
 13
 14
 15

In [29]:
#vertical concatenation
vcat(cvec1, cvec2, cvec3)

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [35]:
#Returns array
[cvec1, cvec2, cvec3]

3-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]
 [11, 12, 13, 14, 15]

In [32]:
#Horizontal concatenation, FYI: Lengths of element vectors should be same
hcat(cvec1, cvec2, cvec3)

5×3 Matrix{Int64}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [33]:
rvec1 = [1 2 3 4 5]
rvec2 = [6 7 8 9 10]
rvec3 = [11 12 13 14 15]

1×5 Matrix{Int64}:
 11  12  13  14  15

In [34]:
hcat(rvec1, rvec2, rvec3)

1×15 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15

In [36]:
[rvec1; rvec2; rvec3]

3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [37]:
[rvec1 rvec2 rvec3]

1×15 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15

In [39]:
m1 =[1 2 3; 4 5 6]
m2 = [11 12 13; 14 15 16]
mver = [m1; m2]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
 11  12  13
 14  15  16

In [40]:
mhor = [m1 m2]

2×6 Matrix{Int64}:
 1  2  3  11  12  13
 4  5  6  14  15  16

In [41]:
emptymt = Matrix(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [42]:
Matrix{Any}(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [43]:
Matrix{Float64}(undef, 3, 2)

3×2 Matrix{Float64}:
 0.0          0.0
 6.9116e-310  6.9116e-310
 6.9116e-310  6.9116e-310

In [44]:
mat = Matrix{Union{Int64, String}}(undef, 3, 4)

3×4 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [46]:
#Data is neither type int64 nor string
mat[3, 4] = 6.78

LoadError: MethodError: Cannot `convert` an object of type 
  Float64 to an object of type 
  Union{Int64, String}
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61

In [47]:
nothing

In [48]:
typeof(nothing)

Nothing

In [49]:
Matrix{Any}(nothing, (2,3))

2×3 Matrix{Any}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [53]:
#Gives bug
#Matrix{Int64}(nothing, (2,3))
Matrix{Union{Int64,Nothing}}(nothing, (2,3))

2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [54]:
missing

missing

In [55]:
typeof(missing)

Missing

In [56]:
Matrix{Union{Missing, String}}(missing, (2,3))

2×3 Matrix{Union{Missing, String}}:
 missing  missing  missing
 missing  missing  missing

In [57]:
reshape(1:15, 3, 5)

3×5 reshape(::UnitRange{Int64}, 3, 5) with eltype Int64:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

In [58]:
reshape(mhor, (4,3))

4×3 Matrix{Int64}:
 1   3  12
 4   6  15
 2  11  13
 5  14  16

In [59]:
zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [60]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [61]:
ones(Int32, 2, 3)

2×3 Matrix{Int32}:
 1  1  1
 1  1  1

In [62]:
trues(2, 2)

2×2 BitMatrix:
 1  1
 1  1

In [63]:
falses(2,2)

2×2 BitMatrix:
 0  0
 0  0

In [64]:
fill(3.14, (3,2))

3×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14
 3.14  3.14

In [65]:
rand(1:20, 3, 5)

3×5 Matrix{Int64}:
 13   4   7  17  17
  4  16  15   8   3
 12  14   5   2   7

In [66]:
#Normally distributed random numbers
randn(3,5)

3×5 Matrix{Float64}:
  1.10925   -0.965283   0.248316  -0.40579    0.144587
  1.31773    1.97081    1.19257    0.160309   0.742443
 -0.543787   0.626436  -1.65113   -0.209939  -2.63127

In [67]:
m1 = reshape(range(12., 23., length=12), (4,3))

4×3 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 4, 3) with eltype Float64:
 12.0  16.0  20.0
 13.0  17.0  21.0
 14.0  18.0  22.0
 15.0  19.0  23.0

In [68]:
m2 = similar(m1)

4×3 Matrix{Float64}:
 6.91161e-310  6.9116e-310   6.91161e-310
 6.91161e-310  6.91161e-310  6.91161e-310
 6.91161e-310  6.91161e-310  6.91161e-310
 6.91161e-310  6.9116e-310   6.91161e-310

In [69]:
m3 = similar(m1, (3,3))

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  6.91161e-310