In [222]:
#Shishir Khanal
#26/11/2022
#Hello World in Julia

3 + 5

8

In [223]:
println("I am running Julia from Jupyter")

I am running Julia from Jupyter


In [224]:
42

42

In [225]:
4.4

4.4

In [226]:
typeof(42)

Int64

In [227]:
typeof(4.4)

Float64

In [228]:
3 + 6 * 7

45

In [229]:
3/56

0.05357142857142857

In [230]:
typeof(3/56)

Float64

In [231]:
grade = 34

34

In [232]:
grade

34

In [233]:
println(grade)

34


In [234]:
rank = 4

4

In [235]:
grade + rank

38

In [236]:
typeof(rank)

Int64

In [237]:
pi

π = 3.1415926535897...

In [238]:
100 % 3

1

In [239]:
2 ^ 3

8

In [240]:
#This is comment

In [241]:
#= 1st line
2ndline
Third line
=#

In [242]:
s1 = "This is Julia"

"This is Julia"

In [243]:
typeof(s1)

String

In [244]:
s2 = """This is first line.
This is second line.
This is third line."""

"This is first line.\nThis is second line.\nThis is third line."

In [245]:
println(s2)

This is first line.
This is second line.
This is third line.


In [246]:
s3 = """It "is" raining outside" """

"It \"is\" raining outside\" "

In [247]:
println(s3)

It "is" raining outside" 


In [248]:
println("My grade is 12")

My grade is 12


In [249]:
grade

34

In [250]:
println("My grade is $grade")

My grade is 34


In [251]:
println("My grade is $(grade+5)")

My grade is 39


In [252]:
m1 = "I love "
m2 = "Julia";

In [253]:
string(m1, m2)

"I love Julia"

In [254]:
string(m1, "classic ", m2)

"I love classic Julia"

In [255]:
m2 = "Julia "

"Julia "

In [256]:
m2 ^ 100

"Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia J" ⋯ 58 bytes ⋯ " Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia Julia "

In [257]:
 m1

"I love "

In [258]:
m1[1]

'I': ASCII/Unicode U+0049 (category Lu: Letter, uppercase)

In [259]:
m1[3]

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

In [260]:
#m1[start index: end index]
#Upper bound is always included
m1[3:6]

"love"

In [261]:
ch = 'm'

'm': ASCII/Unicode U+006D (category Ll: Letter, lowercase)

In [262]:
[3, 5, 9]

3-element Vector{Int64}:
 3
 5
 9

In [263]:
[3, 5, 9] + [1, 2, 3]

3-element Vector{Int64}:
  4
  7
 12

In [264]:
arr = ["Hello", 2, 45.7, true]

4-element Vector{Any}:
     "Hello"
    2
   45.7
 true

In [265]:
length(arr)

4

In [266]:
typeof(arr)

Vector{Any} (alias for Array{Any, 1})

In [267]:
maximum([3, 5, 9])

9

In [268]:
arr[3]

45.7

In [269]:
arr[2:4]

3-element Vector{Any}:
    2
   45.7
 true

In [270]:
arr[4:4]

1-element Vector{Any}:
 true

In [271]:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [272]:
ones(4)

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [273]:
println(arr)

Any["Hello", 2, 45.7, true]


In [274]:
push!(arr, "34")

5-element Vector{Any}:
     "Hello"
    2
   45.7
 true
     "34"

In [275]:
println(arr)

Any["Hello", 2, 45.7, true, "34"]


In [276]:
sort([3, 5, -1])

3-element Vector{Int64}:
 -1
  3
  5

In [277]:
range(1, stop=100)

1:100

In [278]:
range(-10,step=5, length=10)

-10:5:35

In [279]:
range(-10, length=10)

-10:-1

In [280]:
arr

5-element Vector{Any}:
     "Hello"
    2
   45.7
 true
     "34"

In [281]:
arr1 = arr
#Doesn't create a new copy

5-element Vector{Any}:
     "Hello"
    2
   45.7
 true
     "34"

In [282]:
arr1[1] = "Bye"

"Bye"

In [283]:
println(arr1, arr)

Any["Bye", 2, 45.7, true, "34"]Any["Bye", 2, 45.7, true, "34"]


In [284]:
arr2 = copy(arr)

5-element Vector{Any}:
     "Bye"
    2
   45.7
 true
     "34"

In [285]:
arr2[1] = "Julia"

"Julia"

In [286]:
println(arr, arr2)

Any["Bye", 2, 45.7, true, "34"]Any["Julia", 2, 45.7, true, "34"]


In [287]:
arr

5-element Vector{Any}:
     "Bye"
    2
   45.7
 true
     "34"

In [288]:
in(2, arr)
#Does 2 exist in arr?

true

In [289]:
in("2", arr)
#Does 2(string) exist in arr?

false

In [290]:
#Tuples

In [291]:
t1 = (3, 6, true)

(3, 6, true)

In [292]:
typeof(t1)

Tuple{Int64, Int64, Bool}

In [293]:
t1[2]

6

In [294]:
#t1[2] = "hello"
#Once defined tuple values can't be changed

In [295]:
length(t1)

3

In [296]:
#Dictionary

In [297]:
#=
Jogn - 555
Alice - 111
Bob - 333
=#
phonebook = Dict("John" => "555", "Alice" => "111", "Bob" => "333")

Dict{String, String} with 3 entries:
  "John"  => "555"
  "Alice" => "111"
  "Bob"   => "333"

In [298]:
keys(phonebook)

KeySet for a Dict{String, String} with 3 entries. Keys:
  "John"
  "Alice"
  "Bob"

In [299]:
values(phonebook)

ValueIterator for a Dict{String, String} with 3 entries. Values:
  "555"
  "111"
  "333"

In [300]:
phonebook["John"]

"555"

In [301]:
for (k, v) in phonebook
    println("$k, $v")
end

John, 555
Alice, 111
Bob, 333


In [302]:
collect(keys(phonebook))

3-element Vector{String}:
 "John"
 "Alice"
 "Bob"

In [303]:
haskey(phonebook, "John")

true

In [304]:
haskey(phonebook, "John1")

false

In [305]:
#Sets

In [306]:
s1 = Set([1,3,6,6])

Set{Int64} with 3 elements:
  6
  3
  1

In [307]:
s2 = Set([3, 6, 4, 3])

Set{Int64} with 3 elements:
  4
  6
  3

In [308]:
union(s1, s2)

Set{Int64} with 4 elements:
  4
  6
  3
  1

In [309]:
intersect(s1, s2)

Set{Int64} with 2 elements:
  6
  3

In [310]:
issubset(s1, s2)

false

In [311]:
#Decision making

In [312]:
N = 20

20

In [313]:
if N > 0
    println("N is +ve")
else
    println("N is -ve")
end

N is +ve


In [314]:
if N > 25
    println("Number is greater than 25")
elseif (N > 0 && N < 25)
    println("Number is between 0 an 25")
else
    println("Number is negative")
end

Number is between 0 an 25


In [315]:
#Looping

In [316]:
for i = 1:25
    println(i)
end


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [317]:
for i = 1:5, j = 1:5
    println(i, ":", j)
end

1:1
1:2
1:3
1:4
1:5
2:1
2:2
2:3
2:4
2:5
3:1
3:2
3:3
3:4
3:5
4:1
4:2
4:3
4:4
4:5
5:1
5:2
5:3
5:4
5:5


In [318]:
arr = [3, 5, "Hello"]

3-element Vector{Any}:
 3
 5
  "Hello"

In [319]:
for val in arr
    println(val)
end

3
5
Hello


In [320]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [321]:
i = 1
while i < 6
    println(i)
    i = i + 1
end

1
2
3
4
5


In [322]:
#Functions

In [323]:
function welcome()
    println("Hello World")
end

welcome (generic function with 1 method)

In [324]:
welcome()

Hello World


In [325]:
function welcome1(name)
    println("Hello $name")
end

welcome1 (generic function with 1 method)

In [326]:
#welcome1()
#throws an error

In [327]:
welcome1("World")

Hello World


In [328]:
welcome1("Julia")

Hello Julia


In [329]:
welcome2(name) = println("Hello $name")

welcome2 (generic function with 1 method)

In [330]:
welcome2("Julia")

Hello Julia


In [331]:
welcome3 = name -> println("Hello $name")

#9 (generic function with 1 method)

In [332]:
welcome3("data")

Hello data


In [333]:
function add(x, y)
    z = x + y
    return z
end

add (generic function with 1 method)

In [334]:
add(4,6)

10

In [335]:
arr = [2,3, 6, 0, -4]

5-element Vector{Int64}:
  2
  3
  6
  0
 -4

In [336]:
sort(arr)

5-element Vector{Int64}:
 -4
  0
  2
  3
  6

In [337]:
arr

5-element Vector{Int64}:
  2
  3
  6
  0
 -4

In [338]:
sort!(arr)
#modify original variable 'arr'

5-element Vector{Int64}:
 -4
  0
  2
  3
  6

In [339]:
arr

5-element Vector{Int64}:
 -4
  0
  2
  3
  6

In [340]:
function f1(x)
    x^2
end

f1 (generic function with 1 method)

In [341]:
map(f1, arr)

5-element Vector{Int64}:
 16
  0
  4
  9
 36

In [342]:
#Packages

In [343]:
using Pkg

In [344]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl:675


Dict{String, VersionNumber} with 5 entries:
  "CSV"        => v"0.10.7"
  "Tables"     => v"1.10.0"
  "JSONTables" => v"1.0.3"
  "IJulia"     => v"1.23.3"
  "DataFrames" => v"1.4.3"

In [345]:
Pkg.rm("Statistics")

    Updating `~/.julia/environments/v1.8/Project.toml`
  [10745b16] - Statistics
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [346]:
Pkg.dependencies()

Dict{Base.UUID, Pkg.API.PackageInfo} with 82 entries:
  UUID("59287772-0a20-5a39… => PackageInfo("Formatting", v"0.4.2", "8339d610432…
  UUID("e2d170a0-9d28-54be… => PackageInfo("DataValueInterfaces", v"1.0.0", "bf…
  UUID("a8cc5b0e-0ffa-5ad4… => PackageInfo("Crayons", v"4.1.1", "249fe38abf76d4…
  UUID("bac558e1-5e72-5ebc… => PackageInfo("OrderedCollections", v"1.4.1", "85f…
  UUID("29816b5a-b9ab-546f… => PackageInfo("LibSSH2_jll", v"1.10.2+0", nothing,…
  UUID("81def892-9a0e-5fdd… => PackageInfo("VersionParsing", v"1.3.0", "58d6e80…
  UUID("3bb67fe8-82b1-5028… => PackageInfo("TranscodingStreams", v"0.9.9", "8a7…
  UUID("b964fa9f-0449-5b57… => PackageInfo("LaTeXStrings", v"1.3.0", "f2355693d…
  UUID("b85f4697-e234-5449… => PackageInfo("SoftGlobalScope", v"1.1.0", "986ec2…
  UUID("336ed68f-0bac-5ca0… => PackageInfo("CSV", v"0.10.7", "c5fd7cd27ac4aed0a…
  UUID("a63ad114-7e13-5084… => PackageInfo("Mmap", nothing, nothing, false, fal…
  UUID("14a3606d-f60d-562e… => PackageInfo("MozillaCACe

In [347]:
Pkg.add("Statistics")

   Resolving package versions...
    Updating `~/.julia/environments/v1.8/Project.toml`
  [10745b16] + Statistics
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [348]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /cache/build/default-amdci5-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl:675


Dict{String, VersionNumber} with 5 entries:
  "CSV"        => v"0.10.7"
  "Tables"     => v"1.10.0"
  "JSONTables" => v"1.0.3"
  "IJulia"     => v"1.23.3"
  "DataFrames" => v"1.4.3"

In [349]:
using Statistics

In [350]:
mean([3, 7, 9])

6.333333333333333

In [351]:
#Vector and Matrix Processing

In [352]:
using Pkg
Pkg.add("Random")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [353]:
randn(10, 2)

10×2 Matrix{Float64}:
  0.227818  -0.379073
  1.14473   -1.05861
 -1.56938   -0.844171
  0.911133  -0.541124
  0.165618   0.424044
  0.530956   0.425637
  2.37734   -0.0882609
  1.42542    1.82246
 -1.27063   -1.14812
  0.965496   1.71259

In [354]:
using Random 
randstring()

"tfhLGTd6"

In [355]:
randstring('A':'Z', 50)

"DPFVTHFUENTNZNUEBTXGEPTPZYHMPZYQYVEKVCICIRWGVODEQO"

In [356]:
v1 = Vector(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [357]:
reshape(v1, (2, 5))

2×5 Matrix{Int64}:
 1  3  5  7   9
 2  4  6  8  10

In [358]:
ones(3, 5)

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [359]:
zeros(2, 5, 6)

2×5×6 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 5] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 6] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [360]:
using LinearAlgebra

In [361]:
I(4)

4×4 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅
 ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  1

In [362]:
I(10)

10×10 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1

In [363]:
M = [2 4 5;1 2 3;6 7 0] 

3×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0

In [364]:
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

In [365]:
size(M)

(3, 3)

In [366]:
M[1, :]
M[:, 2]

3-element Vector{Int64}:
 4
 2
 7

In [367]:
N = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [368]:
[M N]

3×6 Matrix{Int64}:
 2  4  5  1  2  3
 1  2  3  4  5  6
 6  7  0  7  8  9

In [369]:
[M;N]

6×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [370]:
hcat(M, N)

3×6 Matrix{Int64}:
 2  4  5  1  2  3
 1  2  3  4  5  6
 6  7  0  7  8  9

In [371]:
vcat(M, N)

6×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [372]:
transpose(M)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 2  1  6
 4  2  7
 5  3  0

In [373]:
tr(M)

4

In [374]:
det(M)

5.000000000000001

In [375]:
inv(M)

3×3 Matrix{Float64}:
 -4.2   7.0   0.4
  3.6  -6.0  -0.2
 -1.0   2.0   0.0

In [376]:
M

3×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0

In [377]:
UpperTriangular(M)

3×3 UpperTriangular{Int64, Matrix{Int64}}:
 2  4  5
 ⋅  2  3
 ⋅  ⋅  0

In [378]:
LowerTriangular(M)

3×3 LowerTriangular{Int64, Matrix{Int64}}:
 2  ⋅  ⋅
 1  2  ⋅
 6  7  0

In [379]:
eigvecs(M)

3×3 Matrix{Float64}:
 -0.424033  -0.742562  -0.645135
 -0.292089   0.639301  -0.358268
  0.857251  -0.19974   -0.674866

In [380]:
eigvals(M)

3-element Vector{Float64}:
 -5.352954259951673
 -0.09882411688237432
  9.451778376834048

In [381]:
#Dataframes

In [382]:
Pkg.add("DataFrames")
using DataFrames

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [383]:
DataFrame()

0×0 DataFrame

In [384]:
DataFrame(A=1:4, B = rand(4))

4×2 DataFrame
 Row │ A      B        
     │ Int64  Float64  
─────┼─────────────────
   1 │     1  0.706022
   2 │     2  0.608332
   3 │     3  0.206802
   4 │     4  0.63112

In [385]:
X1 = DataFrame(rand(10,3), :auto)

10×3 DataFrame
 Row │ x1        x2         x3       
     │ Float64   Float64    Float64  
─────┼───────────────────────────────
   1 │ 0.179904  0.222876   0.468106
   2 │ 0.31201   0.0549814  0.507867
   3 │ 0.454247  0.238273   0.344357
   4 │ 0.210249  0.6448     0.208379
   5 │ 0.933275  0.702414   0.914174
   6 │ 0.909735  0.588535   0.260214
   7 │ 0.418997  0.442432   0.54457
   8 │ 0.360252  0.35902    0.936416
   9 │ 0.790326  0.545632   0.10018
  10 │ 0.942377  0.544519   0.202476

In [386]:
Matrix(X1)

10×3 Matrix{Float64}:
 0.179904  0.222876   0.468106
 0.31201   0.0549814  0.507867
 0.454247  0.238273   0.344357
 0.210249  0.6448     0.208379
 0.933275  0.702414   0.914174
 0.909735  0.588535   0.260214
 0.418997  0.442432   0.54457
 0.360252  0.35902    0.936416
 0.790326  0.545632   0.10018
 0.942377  0.544519   0.202476

In [387]:
Pkg.add("Tables")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [388]:
using Tables

In [389]:
tb = Tables.columntable(X1)

(x1 = [0.17990438642381712, 0.3120097790294787, 0.45424705606069427, 0.21024926049707993, 0.9332745265053426, 0.9097351747184736, 0.4189970853745172, 0.36025222115739997, 0.7903257272915502, 0.9423771516593723], x2 = [0.2228755147412641, 0.05498140150965636, 0.23827290774543186, 0.6448003500559807, 0.7024144580837752, 0.5885351430618508, 0.44243173708199324, 0.35902013187003534, 0.5456320977172394, 0.5445193573109056], x3 = [0.46810565051365016, 0.5078671875168738, 0.3443566342015677, 0.20837941246202785, 0.9141741690985625, 0.2602143361409911, 0.544569866431218, 0.9364160086407148, 0.10018011484641076, 0.20247636021362758])

In [390]:
typeof(tb)

NamedTuple{(:x1, :x2, :x3), Tuple{Vector{Float64}, Vector{Float64}, Vector{Float64}}}

In [391]:
tb.x1;
tb.x2;
tb.x3

10-element Vector{Float64}:
 0.46810565051365016
 0.5078671875168738
 0.3443566342015677
 0.20837941246202785
 0.9141741690985625
 0.2602143361409911
 0.544569866431218
 0.9364160086407148
 0.10018011484641076
 0.20247636021362758

In [392]:
X1

10×3 DataFrame
 Row │ x1        x2         x3       
     │ Float64   Float64    Float64  
─────┼───────────────────────────────
   1 │ 0.179904  0.222876   0.468106
   2 │ 0.31201   0.0549814  0.507867
   3 │ 0.454247  0.238273   0.344357
   4 │ 0.210249  0.6448     0.208379
   5 │ 0.933275  0.702414   0.914174
   6 │ 0.909735  0.588535   0.260214
   7 │ 0.418997  0.442432   0.54457
   8 │ 0.360252  0.35902    0.936416
   9 │ 0.790326  0.545632   0.10018
  10 │ 0.942377  0.544519   0.202476

In [393]:
names(X1)

3-element Vector{String}:
 "x1"
 "x2"
 "x3"

In [394]:
size(X1)

(10, 3)

In [395]:
size(X1, 1), size(X1, 2)

(10, 3)

In [396]:
nrow(X1)

10

In [397]:
ncol(X1)

3

In [398]:
describe(X1)
describe(X1, cols=1:2)

2×7 DataFrame
 Row │ variable  mean      min        median    max       nmissing  eltype   
     │ Symbol    Float64   Float64    Float64   Float64   Int64     DataType 
─────┼───────────────────────────────────────────────────────────────────────
   1 │ x1        0.551137  0.179904   0.436622  0.942377         0  Float64
   2 │ x2        0.434348  0.0549814  0.493476  0.702414         0  Float64

In [399]:
eltype.(eachcol(X1))

3-element Vector{DataType}:
 Float64
 Float64
 Float64

In [400]:
first(X1)

DataFrameRow
 Row │ x1        x2        x3       
     │ Float64   Float64   Float64  
─────┼──────────────────────────────
   1 │ 0.179904  0.222876  0.468106

In [401]:
first(X1, 5)

5×3 DataFrame
 Row │ x1        x2         x3       
     │ Float64   Float64    Float64  
─────┼───────────────────────────────
   1 │ 0.179904  0.222876   0.468106
   2 │ 0.31201   0.0549814  0.507867
   3 │ 0.454247  0.238273   0.344357
   4 │ 0.210249  0.6448     0.208379
   5 │ 0.933275  0.702414   0.914174

In [402]:
last(X1);
last(X1, 2)

2×3 DataFrame
 Row │ x1        x2        x3       
     │ Float64   Float64   Float64  
─────┼──────────────────────────────
   1 │ 0.790326  0.545632  0.10018
   2 │ 0.942377  0.544519  0.202476

In [403]:
#First 7 rows of only x1 and x2 but not x3
#X1[Row, col]
X1[1:7, 1:2]

7×2 DataFrame
 Row │ x1        x2        
     │ Float64   Float64   
─────┼─────────────────────
   1 │ 0.179904  0.222876
   2 │ 0.31201   0.0549814
   3 │ 0.454247  0.238273
   4 │ 0.210249  0.6448
   5 │ 0.933275  0.702414
   6 │ 0.909735  0.588535
   7 │ 0.418997  0.442432

In [404]:
X1[1:7, :]

7×3 DataFrame
 Row │ x1        x2         x3       
     │ Float64   Float64    Float64  
─────┼───────────────────────────────
   1 │ 0.179904  0.222876   0.468106
   2 │ 0.31201   0.0549814  0.507867
   3 │ 0.454247  0.238273   0.344357
   4 │ 0.210249  0.6448     0.208379
   5 │ 0.933275  0.702414   0.914174
   6 │ 0.909735  0.588535   0.260214
   7 │ 0.418997  0.442432   0.54457

In [405]:
X1[:, 3]

10-element Vector{Float64}:
 0.46810565051365016
 0.5078671875168738
 0.3443566342015677
 0.20837941246202785
 0.9141741690985625
 0.2602143361409911
 0.544569866431218
 0.9364160086407148
 0.10018011484641076
 0.20247636021362758

In [406]:
X1[:, Between(:x1, :x3)]

10×3 DataFrame
 Row │ x1        x2         x3       
     │ Float64   Float64    Float64  
─────┼───────────────────────────────
   1 │ 0.179904  0.222876   0.468106
   2 │ 0.31201   0.0549814  0.507867
   3 │ 0.454247  0.238273   0.344357
   4 │ 0.210249  0.6448     0.208379
   5 │ 0.933275  0.702414   0.914174
   6 │ 0.909735  0.588535   0.260214
   7 │ 0.418997  0.442432   0.54457
   8 │ 0.360252  0.35902    0.936416
   9 │ 0.790326  0.545632   0.10018
  10 │ 0.942377  0.544519   0.202476

In [407]:
X1.x4 = rand(10)

10-element Vector{Float64}:
 0.47887796448452846
 0.17045428299191334
 0.20424258731990852
 0.7609808004369392
 0.7679709452011922
 0.7041923436724514
 0.30885912074897526
 0.18680593051878225
 0.25867235371235553
 0.8073591274971317

In [408]:
X1

10×4 DataFrame
 Row │ x1        x2         x3        x4       
     │ Float64   Float64    Float64   Float64  
─────┼─────────────────────────────────────────
   1 │ 0.179904  0.222876   0.468106  0.478878
   2 │ 0.31201   0.0549814  0.507867  0.170454
   3 │ 0.454247  0.238273   0.344357  0.204243
   4 │ 0.210249  0.6448     0.208379  0.760981
   5 │ 0.933275  0.702414   0.914174  0.767971
   6 │ 0.909735  0.588535   0.260214  0.704192
   7 │ 0.418997  0.442432   0.54457   0.308859
   8 │ 0.360252  0.35902    0.936416  0.186806
   9 │ 0.790326  0.545632   0.10018   0.258672
  10 │ 0.942377  0.544519   0.202476  0.807359

In [409]:
#Reading & Writing DataFrames

In [410]:
df = DataFrame(A=[true, false, true], B=[23, 45, 67], C=['a', 'c', 'b'])

3×3 DataFrame
 Row │ A      B      C    
     │ Bool   Int64  Char 
─────┼────────────────────
   1 │  true     23  a
   2 │ false     45  c
   3 │  true     67  b

In [411]:
Pkg.add("CSV")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [412]:
using CSV

In [413]:
CSV.write("df.csv", df)

"df.csv"

In [414]:
new_df = CSV.read("df.csv", DataFrame)

3×3 DataFrame
 Row │ A      B      C       
     │ Bool   Int64  String1 
─────┼───────────────────────
   1 │  true     23  a
   2 │ false     45  c
   3 │  true     67  b

In [415]:
Pkg.add("Serialization")
using Serialization

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [416]:
open("df.bin", "w") do io
    serialize(io, df)
end

In [417]:
open(deserialize, "df.bin")

3×3 DataFrame
 Row │ A      B      C    
     │ Bool   Int64  Char 
─────┼────────────────────
   1 │  true     23  a
   2 │ false     45  c
   3 │  true     67  b

In [418]:
Pkg.add("JSONTables")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [419]:
using JSONTables

In [420]:
open(io -> arraytable(io, df), "df.json", "w")

80

In [421]:
open(jsontable, "df.json") |> DataFrame

3×3 DataFrame
 Row │ A      B      C      
     │ Bool   Int64  String 
─────┼──────────────────────
   1 │  true     23  a
   2 │ false     45  c
   3 │  true     67  b

In [422]:
#Row and Column Related operations on DataFrames

In [423]:
M1 = DataFrame(rand(5, 4), :auto)

5×4 DataFrame
 Row │ x1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [424]:
rename(M1, :x1 => :c1)

5×4 DataFrame
 Row │ c1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [425]:
M1

5×4 DataFrame
 Row │ x1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [426]:
rename!(M1, :x1 => :c1)

5×4 DataFrame
 Row │ c1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [427]:
M1

5×4 DataFrame
 Row │ c1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [428]:
rename(M1, [:c1, :c2, :c3, :c4])

5×4 DataFrame
 Row │ c1        c2        c3        c4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [429]:
#Rename rows to a, b, c,d
rename(M1, string.('a':'d'))

5×4 DataFrame
 Row │ a         b         c         d         
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [430]:
M2 = DataFrame(rand(5,4), :auto)

5×4 DataFrame
 Row │ x1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.313919  0.443422  0.842241  0.742186
   2 │ 0.146726  0.205122  0.272065  0.0965629
   3 │ 0.962569  0.474664  0.278137  0.950534
   4 │ 0.836253  0.885966  0.860218  0.27804
   5 │ 0.315536  0.385046  0.803888  0.798471

In [431]:
#M1 and M2 hae the same row names so they can't be simply concatenated
hcat(M1, M2, makeunique=true)

5×8 DataFrame
 Row │ c1        x2        x3        x4         x1        x2_1      x3_1       ⋯
     │ Float64   Float64   Float64   Float64    Float64   Float64   Float64    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227   0.313919  0.443422  0.842241   ⋯
   2 │ 0.398605  0.195815  0.627964  0.0561729  0.146726  0.205122  0.272065
   3 │ 0.975973  0.638358  0.980977  0.591451   0.962569  0.474664  0.278137
   4 │ 0.972159  0.506985  0.947555  0.437553   0.836253  0.885966  0.860218
   5 │ 0.397127  0.514557  0.493713  0.490845   0.315536  0.385046  0.803888   ⋯
                                                                1 column omitted

In [432]:
#vcat(M1, M2)
rename!(M1, :c1=>:x1)

5×4 DataFrame
 Row │ x1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845

In [433]:
vcat(M1, M2)

10×4 DataFrame
 Row │ x1        x2        x3        x4        
     │ Float64   Float64   Float64   Float64   
─────┼─────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227
   2 │ 0.398605  0.195815  0.627964  0.0561729
   3 │ 0.975973  0.638358  0.980977  0.591451
   4 │ 0.972159  0.506985  0.947555  0.437553
   5 │ 0.397127  0.514557  0.493713  0.490845
   6 │ 0.313919  0.443422  0.842241  0.742186
   7 │ 0.146726  0.205122  0.272065  0.0965629
   8 │ 0.962569  0.474664  0.278137  0.950534
   9 │ 0.836253  0.885966  0.860218  0.27804
  10 │ 0.315536  0.385046  0.803888  0.798471

In [434]:
[M1 DataFrame(A=[1, 2, 3, 4, 5])]

5×5 DataFrame
 Row │ x1        x2        x3        x4         A     
     │ Float64   Float64   Float64   Float64    Int64 
─────┼────────────────────────────────────────────────
   1 │ 0.729509  0.883271  0.48758   0.838227       1
   2 │ 0.398605  0.195815  0.627964  0.0561729      2
   3 │ 0.975973  0.638358  0.980977  0.591451       3
   4 │ 0.972159  0.506985  0.947555  0.437553       4
   5 │ 0.397127  0.514557  0.493713  0.490845       5

In [435]:
insertcols!(M1, 3, :newcol => [1, 2, 3, 4, 5])

5×5 DataFrame
 Row │ x1        x2        newcol  x3        x4        
     │ Float64   Float64   Int64   Float64   Float64   
─────┼─────────────────────────────────────────────────
   1 │ 0.729509  0.883271       1  0.48758   0.838227
   2 │ 0.398605  0.195815       2  0.627964  0.0561729
   3 │ 0.975973  0.638358       3  0.980977  0.591451
   4 │ 0.972159  0.506985       4  0.947555  0.437553
   5 │ 0.397127  0.514557       5  0.493713  0.490845

In [436]:
M1

5×5 DataFrame
 Row │ x1        x2        newcol  x3        x4        
     │ Float64   Float64   Int64   Float64   Float64   
─────┼─────────────────────────────────────────────────
   1 │ 0.729509  0.883271       1  0.48758   0.838227
   2 │ 0.398605  0.195815       2  0.627964  0.0561729
   3 │ 0.975973  0.638358       3  0.980977  0.591451
   4 │ 0.972159  0.506985       4  0.947555  0.437553
   5 │ 0.397127  0.514557       5  0.493713  0.490845

In [437]:
M1[:, [:x2,:x3]]

5×2 DataFrame
 Row │ x2        x3       
     │ Float64   Float64  
─────┼────────────────────
   1 │ 0.883271  0.48758
   2 │ 0.195815  0.627964
   3 │ 0.638358  0.980977
   4 │ 0.506985  0.947555
   5 │ 0.514557  0.493713

In [438]:
cp_M1 = copy(M1)

5×5 DataFrame
 Row │ x1        x2        newcol  x3        x4        
     │ Float64   Float64   Int64   Float64   Float64   
─────┼─────────────────────────────────────────────────
   1 │ 0.729509  0.883271       1  0.48758   0.838227
   2 │ 0.398605  0.195815       2  0.627964  0.0561729
   3 │ 0.975973  0.638358       3  0.980977  0.591451
   4 │ 0.972159  0.506985       4  0.947555  0.437553
   5 │ 0.397127  0.514557       5  0.493713  0.490845

In [439]:
M1 == cp_M1

true

In [440]:
#Sort M1 on the basis of x1 col
sort(M1, :x1)

5×5 DataFrame
 Row │ x1        x2        newcol  x3        x4        
     │ Float64   Float64   Int64   Float64   Float64   
─────┼─────────────────────────────────────────────────
   1 │ 0.397127  0.514557       5  0.493713  0.490845
   2 │ 0.398605  0.195815       2  0.627964  0.0561729
   3 │ 0.729509  0.883271       1  0.48758   0.838227
   4 │ 0.972159  0.506985       4  0.947555  0.437553
   5 │ 0.975973  0.638358       3  0.980977  0.591451

In [441]:
deleteat!(M1, 4)

4×5 DataFrame
 Row │ x1        x2        newcol  x3        x4        
     │ Float64   Float64   Int64   Float64   Float64   
─────┼─────────────────────────────────────────────────
   1 │ 0.729509  0.883271       1  0.48758   0.838227
   2 │ 0.398605  0.195815       2  0.627964  0.0561729
   3 │ 0.975973  0.638358       3  0.980977  0.591451
   4 │ 0.397127  0.514557       5  0.493713  0.490845

In [442]:
#Based on some logical condition ,filter your data
# Look at rows of x1 column and only retrieve the rows that are greater than 0.6 in the rows of x1
filter( r -> r.x1 > 0.6, M1)

2×5 DataFrame
 Row │ x1        x2        newcol  x3        x4       
     │ Float64   Float64   Int64   Float64   Float64  
─────┼────────────────────────────────────────────────
   1 │ 0.729509  0.883271       1  0.48758   0.838227
   2 │ 0.975973  0.638358       3  0.980977  0.591451